/**
 * Sync configuration from theme-config.ts to other config files
 *
 * This script synchronizes theme configuration with:
 * - content/config/config.json (application branding)
 * - project.js (production domain)
 *
 * Run with: node scripts/sync-config.js
 */

const fs = require("fs");
const path = require("path");

// Default theme values (synced from config/theme-config.ts)
// Update these manually if you change the TypeScript config
const themeConfig = {
  project: {
    domain: "tienholzdesign.at",
    applicationName: "Tien Holz Design",
    authors: [
      {
        name: "Tien Holz Design",
        url: "tienholzdesign.at",
      },
    ],
  },
};

const updateJsonConfig = () => {
  const configPath = path.join(__dirname, "../content/config/config.json");
  const newConfig = {
    applicationName: themeConfig.project.applicationName,
    authors: themeConfig.project.authors,
  };

  fs.writeFileSync(configPath, JSON.stringify(newConfig, null, 2), "utf8");
  console.log(`✓ Updated ${configPath}`);
};

const generateProjectJs = () => {
  const projectPath = path.join(__dirname, "../project.js");
  const domain = themeConfig.project.domain;

  const content = `/**
 * ⚠️  AUTO-GENERATED FILE
 * 
 * This file is generated by scripts/sync-config.js
 * Do NOT edit manually. Instead, update config/theme-config.ts
 * and run: pnpm run sync-config
 */

module.exports = {
  url: "${domain}" /* Update domain in config/theme-config.ts */,
};
`;

  fs.writeFileSync(projectPath, content, "utf8");
  console.log(`✓ Generated ${projectPath}`);
};

try {
  updateJsonConfig();
  generateProjectJs();
  console.log("\n✓ Configuration synchronized successfully!");
  console.log(
    "\n⚠️  Note: If you've changed values in config/theme-config.ts,",
  );
  console.log(
    "   please manually update the values at the top of this script:",
  );
  console.log("   - themeConfig.project.domain");
  console.log("   - themeConfig.project.applicationName");
  console.log("   - themeConfig.project.authors");
} catch (error) {
  console.error("✗ Error syncing configuration:", error.message);
  process.exit(1);
}
